[package]
name = "stylus-chess"
version = "0.1.5"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/OffchainLabs/stylus-chess"
repository = "https://github.com/OffchainLabs/stylus-chess"
keywords = ["arbitrum", "ethereum", "stylus", "alloy"]
description = "Onchain Chess in Rust with Arbitrum Stylus"

[dependencies]
alloy-primitives = { version = "1.0.1", default-features = false }
alloy-sol-types = { version = "1.0.1", default-features = false }
stylus-sdk = { version = "0.10.0-beta.1", features = ["debug"]}
chess-engine = "0.1.2"

[features]
default = ["mini-alloc"]
export-abi = ["stylus-sdk/export-abi"]
debug = ["stylus-sdk/debug"]
mini-alloc = ["stylus-sdk/mini-alloc"]
contract-client-gen = []

[[bin]]
name = "stylus-chess"
path = "src/main.rs"

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
opt-level = "s"
